// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXYct8HLIyYw8O-2YWvv2lwwffD5ryvg4',
    appId: '1:714547570522:web:d8e4f5a69ca7e804b6b563',
    messagingSenderId: '714547570522',
    projectId: 'tiner-test-5f6d6',
    authDomain: 'tiner-test-5f6d6.firebaseapp.com',
    storageBucket: 'tiner-test-5f6d6.appspot.com',
    measurementId: 'G-G5X1N5XWRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ5whVPzOvHogRaZpIBKkpop5wiPVdWJk',
    appId: '1:714547570522:android:0d04449a88dff768b6b563',
    messagingSenderId: '714547570522',
    projectId: 'tiner-test-5f6d6',
    storageBucket: 'tiner-test-5f6d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnJ4bcnz1G8s4JRTe2AvlId-466NTfhfY',
    appId: '1:714547570522:ios:d8ef6cd4ea4a4f46b6b563',
    messagingSenderId: '714547570522',
    projectId: 'tiner-test-5f6d6',
    storageBucket: 'tiner-test-5f6d6.appspot.com',
    iosClientId: '714547570522-4il3bc13lp5ohs8dt8gnfqkn551gvb3m.apps.googleusercontent.com',
    iosBundleId: 'com.fensterseifer.tinderNew',
  );
}
